# Generated by Django 6.0.1 on 2026-05-13 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('numero_personas', models.IntegerField()),
                ('tipo_visita', models.CharField(choices=[('cabana', 'Cabaña'), ('camping', 'Camping')], max_length=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='parks.parque')),
            ],
        ),
    ]
