# Generated by Django 6.0.4 on 2026-06-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservacion',
            options={'verbose_name': 'Reservación', 'verbose_name_plural': 'Reservaciones'},
        ),
    ]
