# Generated by Django 6.0.1 on 2026-05-13 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('tiene_cabanas', models.BooleanField(default=False)),
                ('capacidad_maxima', models.IntegerField()),
                ('estatus_parque', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenParque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('es_principal', models.BooleanField(default=False)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='parks.parque')),
            ],
        ),
    ]
